plugins { id 'com.android.application' }

android {
    namespace 'mr.bankily.app'
    compileSdk 35

    defaultConfig {
        applicationId 'mr.bankily.app'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
